In [1]:
import sys
sys.executable

'/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5'

In [39]:
import line_profiler
import IPython
ip = IPython.get_ipython()
ip.define_magic('lprun', line_profiler.magic_lprun)

In [2]:
!pwd

/Users/mz/dev/python/programe/PythonforDataAnalysis/ch03


In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
import numpy as np
from numpy.random import randn

In [8]:
data = np.array([x for x in range(1,10)])
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
data * 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
data + data 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
data.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
data.shape

(9,)

In [14]:
data.dtype

dtype('int64')

In [15]:
data.ndim

1

In [17]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
np.empty((2,3))

array([[  0.00000000e+000,   0.00000000e+000,   2.12325858e-314],
       [  2.12326586e-314,   0.00000000e+000,   4.17201482e-309]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.asarray((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [22]:
d = !ls
d

['add_script.py', 'ipython_base.ipynb', 'ipython_bug.py', 'np_base.ipynb']

In [23]:
paths = !echo$PATH
paths

['/bin/sh: echo/usr/local/go/bin:/Users/mz/dev/bin/gradle-2.11/bin:/Users/mz/dev/bin/apache-ant-1.9.6/bin:/Users/mz/dev/bin/apache-maven-3.3.3/bin:/Users/mz/Library/Android/sdk/platform-tools:/Users/mz/Library/Android/sdk/tools:/Users/mz/Library/Android/sdk/build-tools/23.0.0:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/mz/dev/bin/scala-2.11.7/bin:/Users/mz/dev/bin/spark-1.6.0/bin:/usr/local/bin/pys:/Users/mz/.nvm/versions/node/v5.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin: No such file or directory']

In [24]:
!atom cprof_example.py

In [25]:
!python -m cProfile cprof_example.py

Largest one we saw : 10.2670263504
         52500 function calls (50539 primitive calls) in 0.145 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        6    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:1043(__import__)
      304    0.001    0.000    0.001    0.000 <frozen importlib._bootstrap>:119(release)
      132    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:159(__init__)
      132    0.000    0.000    0.002    0.000 <frozen importlib._bootstrap>:163(__enter__)
      132    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap>:170(__exit__)
      304    0.001    0.000    0.001    0.000 <frozen importlib._bootstrap>:176(_get_module_lock)
      131    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:190(cb)
      172    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap>:195(_lock_unlock_module)
    180/1    0.000    0.000    0.137    0.137 <frozen i

In [28]:
!python -m cProfile -s cumulative cprof_example.py

Largest one we saw : 10.956171262
         52500 function calls (50539 primitive calls) in 0.129 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.000    0.000    0.169    0.042 __init__.py:1(<module>)
    116/1    0.003    0.000    0.129    0.129 {built-in method builtins.exec}
        1    0.000    0.000    0.129    0.129 cprof_example.py:4(<module>)
    132/1    0.001    0.000    0.123    0.123 <frozen importlib._bootstrap>:966(_find_and_load)
    132/1    0.001    0.000    0.122    0.122 <frozen importlib._bootstrap>:939(_find_and_load_unlocked)
    128/1    0.001    0.000    0.121    0.121 <frozen importlib._bootstrap>:659(_load_unlocked)
    110/1    0.000    0.000    0.121    0.121 <frozen importlib._bootstrap_external>:656(exec_module)
    180/1    0.000    0.000    0.121    0.121 <frozen importlib._bootstrap>:214(_call_with_frames_removed)
        1    0.000    0.000    0.121    0.121 __init__.py:106

In [30]:
%run -p -s cumulative cprof_example.py

Largest one we saw : 10.4499573951
 

In [35]:
def add_and_sum(x,y):
    added = x + y
    summed = added.sum(axis=1)
    return summed
def call_function():
    x = randn(1000,1000)
    y = randn(1000,1000)
    return add_and_sum(x,y)


In [36]:
x = randn(1000,1000)
y = randn(1000,1000)
%prun add_and_sum(x,y)

In [40]:
%lprun -f add_and_sum add_and_sum(x,y)

In [42]:
%lprun -f add_and_sum -f call_function call_function()